# Generated by Django 3.1.1 on 2020-09-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Publication',
        ),
    ]
